name: Run Cron Job

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  call-cron-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call the cron endpoint
        run: curl -X POST https://www.dextradtechnologies.co.za/api/cron
